In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("quikr_car (1).csv")

In [2]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [3]:
# cleaning 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [4]:
df.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [5]:
df.dropna(inplace=True)

In [6]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,"2,70,000","50,000 kms",Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,"1,10,000","30,000 kms",Diesel
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel

In [7]:
df["name"] = df["name"].str.split().str.slice(start=1,stop=3).str.join(" ")

In [8]:
df["company"].unique()

array(['Hyundai', 'Mahindra', 'Maruti', 'Ford', 'Skoda', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat', 'Force',
       'Mercedes', 'Land', 'Jaguar', 'Jeep', 'Volvo'], dtype=object)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 837 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        837 non-null    object
 1   company     837 non-null    object
 2   year        837 non-null    object
 3   Price       837 non-null    object
 4   kms_driven  837 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 45.8+ KB

In [10]:
df["year"] = df["year"].astype(int)

In [11]:
df

                  name   company  year          Price    kms_driven fuel_type
0          Santro Xing   Hyundai  2007         80,000    45,000 kms    Petrol
1           Jeep CL550  Mahindra  2006       4,25,000        40 kms    Diesel
2          Suzuki Alto    Maruti  2018  Ask For Price    22,000 kms    Petrol
3            Grand i10   Hyundai  2014       3,25,000    28,000 kms    Petrol
4    EcoSport Titanium      Ford  2014       5,75,000    36,000 kms    Diesel
..                 ...       ...   ...            ...           ...       ...
883        Suzuki Ritz    Maruti  2011       2,70,000    50,000 kms    Petrol
885          Indica V2      Tata  2009       1,10,000    30,000 kms    Diesel
886      Corolla Altis    Toyota  2009       3,00,000  1,32,000 kms    Petrol
888            Zest XM      Tata  2018       2,60,000    27,000 kms    Diesel
889          Quanto C8  Mahindra  2013       3,90,000    40,000 kms    Diesel

[837 rows x 6 columns]

In [12]:
df = df[df["Price"] != "Ask For Price"]

In [13]:
df["Price"] = df["Price"].str.replace(",","")

/var/folders/q1/svk0hqb94fzdz050kv_bm58h0000gn/T/ipykernel_27498/3802983802.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price"] = df["Price"].str.replace(",","")

In [14]:
df["Price"] = df["Price"].astype(int)

/var/folders/q1/svk0hqb94fzdz050kv_bm58h0000gn/T/ipykernel_27498/1202961789.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price"] = df["Price"].astype(int)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.6+ KB

In [16]:
df["kms_driven"].unique()

array(['45,000 kms', '40 kms', '28,000 kms', '36,000 kms', '41,000 kms',
       '25,000 kms', '24,530 kms', '60,000 kms', '30,000 kms',
       '32,000 kms', '48,660 kms', '4,000 kms', '16,934 kms',
       '43,000 kms', '35,550 kms', '39,522 kms', '39,000 kms',
       '55,000 kms', '72,000 kms', '15,975 kms', '70,000 kms',
       '23,452 kms', '35,522 kms', '48,508 kms', '15,487 kms',
       '82,000 kms', '20,000 kms', '68,000 kms', '38,000 kms',
       '27,000 kms', '33,000 kms', '46,000 kms', '16,000 kms',
       '47,000 kms', '35,000 kms', '30,874 kms', '15,000 kms',
       '29,685 kms', '1,30,000 kms', '19,000 kms', '54,000 kms',
       '13,000 kms', '38,200 kms', '22,000 kms', '50,000 kms',
       '13,500 kms', '3,600 kms', '45,863 kms', '60,500 kms',
       '12,500 kms', '18,000 kms', '13,349 kms', '29,000 kms',
       '44,000 kms', '42,000 kms', '14,000 kms', '49,000 kms',
       '36,200 kms', '51,000 kms', '1,04,000 kms', '33,333 kms',
       '33,600 kms', '5,600 kms', '7,500 kms', '24,330 kms', '65,480 kms',
       '2,00,000 kms', '59,000 kms', '99,000 kms', '2,800 kms',
       '21,000 kms', '11,000 kms', '66,000 kms', '3,000 kms', '7,000 kms',
       '38,500 kms', '37,200 kms', '43,200 kms', '24,800 kms',
       '45,872 kms', '40,000 kms', '11,400 kms', '97,200 kms',
       '52,000 kms', '31,000 kms', '1,75,430 kms', '37,000 kms',
       '65,000 kms', '3,350 kms', '75,000 kms', '62,000 kms',
       '73,000 kms', '2,200 kms', '54,870 kms', '34,580 kms',
       '97,000 kms', '60 kms', '80,200 kms', '3,200 kms', '0,000 kms',
       '5,000 kms', '588 kms', '71,200 kms', '1,75,400 kms', '9,300 kms',
       '56,758 kms', '10,000 kms', '56,450 kms', '56,000 kms',
       '32,700 kms', '9,000 kms', '73 kms', '1,60,000 kms', '58,559 kms',
       '57,000 kms', '1,70,000 kms', '80,000 kms', '6,821 kms',
       '23,000 kms', '34,000 kms', '1,800 kms', '4,00,000 kms',
       '48,000 kms', '90,000 kms', '12,000 kms', '69,900 kms',
       '1,66,000 kms', '122 kms', '0 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '53,000 kms', '35,500 kms', '22,134 kms',
       '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms', '8,000 kms',
       '55,800 kms', '56,400 kms', '72,160 kms', '11,500 kms',
       '1,33,000 kms', '2,000 kms', '88,000 kms', '65,422 kms',
       '1,17,000 kms', '1,50,000 kms', '10,750 kms', '6,800 kms',
       '9,800 kms', '57,923 kms', '30,201 kms', '6,200 kms', '37,518 kms',
       '24,652 kms', '383 kms', '95,000 kms', '3,528 kms', '52,500 kms',
       '47,900 kms', '52,800 kms', '1,95,000 kms', '48,008 kms',
       '48,247 kms', '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '1,37,495 kms',
       '91,200 kms', '1,46,000 kms', '1,00,800 kms', '2,100 kms',
       '2,500 kms', '1,32,000 kms'], dtype=object)

In [17]:
df["kms_driven"] = df["kms_driven"].str.split().str.slice(start=0,stop=1).str.join("").str.replace(",","").astype(int)

/var/folders/q1/svk0hqb94fzdz050kv_bm58h0000gn/T/ipykernel_27498/1395593830.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["kms_driven"] = df["kms_driven"].str.split().str.slice(start=0,stop=1).str.join("").str.replace(",","").astype(int)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.6+ KB

In [19]:
df["fuel_type"].unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [20]:
df

                  name   company  year   Price  kms_driven fuel_type
0          Santro Xing   Hyundai  2007   80000       45000    Petrol
1           Jeep CL550  Mahindra  2006  425000          40    Diesel
3            Grand i10   Hyundai  2014  325000       28000    Petrol
4    EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Figo      Ford  2012  175000       41000    Diesel
..                 ...       ...   ...     ...         ...       ...
883        Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Indica V2      Tata  2009  110000       30000    Diesel
886      Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Zest XM      Tata  2018  260000       27000    Diesel
889          Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [21]:
# split data
X = df[["name","company", "year", "kms_driven" , "fuel_type"]]
y = df["Price"]
from sklearn.model_selection import train_test_split
X_train ,X_test,y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [22]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown="ignore")

In [23]:
ohe.fit(X[["name", "company", "fuel_type"]])

OneHotEncoder(handle_unknown='ignore')

In [24]:
ohe.categories_

[array(['3 Series', '5 Series', '7 Series', 'A3 Cabriolet', 'A4 1.8',
        'A4 2.0', 'A6 2.0', 'A8', 'Accent', 'Accent Executive',
        'Accent GLE', 'Accent GLX', 'Accord', 'Amaze', 'Amaze 1.2',
        'Amaze 1.5', 'Aria Pleasure', 'Beat', 'Beat Diesel', 'Beat LS',
        'Beat LT', 'Beat PS', 'Benz A', 'Benz B', 'Benz C', 'Benz GLA',
        'Bolero DI', 'Bolero Power', 'Bolero SLE', 'Bolt XM', 'Brio',
        'Brio V', 'Brio VX', 'City', 'City 1.5', 'City SV', 'City VX',
        'City ZX', 'Cooper S', 'Corolla', 'Corolla Altis', 'Corolla H2',
        'Creta', 'Creta 1.6', 'Cruze LTZ', 'Duster', 'Duster 110',
        'Duster 110PS', 'Duster 85', 'Duster 85PS', 'Duster RxL',
        'EcoSport', 'EcoSport Ambiente', 'EcoSport Titanium',
        'EcoSport Trend', 'Elantra 1.8', 'Elantra SX', 'Elite i20',
        'Endeavor 4x4', 'Enjoy', 'Enjoy 1.4', 'Eon', 'Eon D', 'Eon Era',
        'Eon Magna', 'Eon Sportz', 'Etios', 'Etios G', 'Etios GD',
        'Etios Liva', 'Fabia', 'Fabia 1.2L', 'Fabia Classic', 'Fiesta',
        'Fiesta SXi', 'Figo', 'Figo Diesel', 'Figo Duratorq',
        'Figo Petrol', 'Fluidic Verna', 'Fortuner', 'Fortuner 3.0',
        'Fusion 1.4', 'GO T', 'Getz', 'Getz GLE', 'Getz Prime', 'Go Plus',
        'Grand i10', 'Ikon 1.3', 'Ikon 1.6', 'Indica', 'Indica V2',
        'Indica eV2', 'Indigo CS', 'Indigo LS', 'Indigo LX',
        'Indigo Marina', 'Indigo eCS', 'Innova 2.0', 'Innova 2.5',
        'Jazz S', 'Jazz VX', 'Jeep CL550', 'Jeep MM', 'Jetta Comfortline',
        'Jetta Highline', 'KUV100', 'KUV100 K8', 'Kwid', 'Kwid 1.0',
        'Kwid RXT', 'Lancer 1.8', 'Laura', 'Linea Emotion', 'Lodgy 85',
        'Logan', 'Logan Diesel', 'Manza', 'Manza Aqua', 'Manza Aura',
        'Manza ELAN', 'Micra XL', 'Micra XV', 'Mobilio', 'Mobilio S',
        'Motors Ambassador', 'Motors Force', 'Motors One', 'Nano',
        'Nano Cx', 'Nano GenX', 'Nano LX', 'Nano Lx', 'Octavia Classic',
        'Pajero Sport', 'Passat Diesel', 'Petra ELX', 'Polo',
        'Polo Comfortline', 'Polo Highline', 'Polo Highline1.2L',
        'Polo Trendline', 'Punto Emotion', 'Q3 2.0', 'Q5 2.0', 'Q7',
        'Qualis', 'Quanto C4', 'Quanto C8', 'Rapid Elegance', 'Redi GO',
        'Rover Freelander', 'S80 Summum', 'Sail 1.2', 'Sail UVA', 'Santro',
        'Santro AE', 'Santro Xing', 'Scala RxL', 'Scorpio', 'Scorpio 2.6',
        'Scorpio LX', 'Scorpio S10', 'Scorpio S4', 'Scorpio SLE',
        'Scorpio SLX', 'Scorpio VLX', 'Scorpio Vlx', 'Scorpio W',
        'Sonata Transform', 'Spark', 'Spark 1.0', 'Spark LS', 'Spark LT',
        'Sumo Gold', 'Sumo Grande', 'Sumo Victa', 'Sunny', 'Sunny XL',
        'Superb 1.8', 'Suzuki 800', 'Suzuki A', 'Suzuki Alto',
        'Suzuki Baleno', 'Suzuki Celerio', 'Suzuki Ciaz', 'Suzuki Dzire',
        'Suzuki Eeco', 'Suzuki Ertiga', 'Suzuki Esteem', 'Suzuki Estilo',
        'Suzuki Maruti', 'Suzuki Omni', 'Suzuki Ritz', 'Suzuki S',
        'Suzuki SX4', 'Suzuki Stingray', 'Suzuki Swift', 'Suzuki Versa',
        'Suzuki Vitara', 'Suzuki Wagon', 'Suzuki Zen', 'TUV300 T4',
        'TUV300 T8', 'Tavera LS', 'Tavera Neo', 'Terrano XL', 'Thar CRDe',
        'Tiago Revotorq', 'Tiago Revotron', 'Tigor Revotron',
        'Vento Comfortline', 'Vento Highline', 'Vento Konekt',
        'Venture EX', 'Verna', 'Verna 1.4', 'Verna 1.6', 'Verna Fluidic',
        'Verna Transform', 'Verna VGT', 'Vista Quadrajet', 'WR V',
        'Wrangler Unlimited', 'X Trail', 'X1', 'X1 sDrive20d',
        'X1 xDrive20d', 'XE XE', 'XF 2.2', 'XUV500', 'XUV500 W10',
        'XUV500 W6', 'XUV500 W8', 'Xcent Base', 'Xcent SX', 'Xylo D2',
        'Xylo E4', 'Xylo E8', 'Yeti Ambition', 'Zest Quadrajet', 'Zest XE',
        'Zest XM', 'i10', 'i10 Era', 'i10 Magna', 'i10 Sportz', 'i20',
        'i20 Active', 'i20 Asta', 'i20 Magna', 'i20 Select', 'i20 Sportz'],
       dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [25]:
from sklearn.compose import make_column_transformer

column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_, handle_unknown='ignore'),['name', 'company', 'fuel_type']),remainder='passthrough')

In [26]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()  #model builing


# pipeline building
from sklearn.pipeline import make_pipeline
pipe_lr = make_pipeline(column_trans,lr)

In [27]:
pipe_lr.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['3 Series', '5 Series', '7 Series', 'A3 Cabriolet', 'A4 1.8',
       'A4 2.0', 'A6 2.0', 'A8', 'Accent', 'Accent Executive',
       'Accent GLE', 'Accent GLX', 'Accord', 'Amaze', 'Amaze 1.2',
       'Amaze 1.5', 'Aria Pleasure', 'Beat', 'Beat Diesel', 'Beat LS',...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)],
                                                                handle_unknown='ignore'),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [28]:
y_pred_lr = pipe_lr.predict(X_test)

In [34]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score

mse_lr  = mean_squared_error(y_test,y_pred_lr)
rmse_lr  = root_mean_squared_error(y_test,y_pred_lr)
r2_lr=  r2_score(y_test,y_pred_lr)

#print(mse_lr)
print(rmse_lr)
print()
print(r2_lr)

671526.7959491515

0.19356499586798437

In [35]:
# Decision Tree
# Random forest
# Xgboost

In [43]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state=4231) # model building

# pipeline building
from sklearn.pipeline import make_pipeline
pipe_dt = make_pipeline(column_trans,dtr)

In [44]:
pipe_dt.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['3 Series', '5 Series', '7 Series', 'A3 Cabriolet', 'A4 1.8',
       'A4 2.0', 'A6 2.0', 'A8', 'Accent', 'Accent Executive',
       'Accent GLE', 'Accent GLX', 'Accord', 'Amaze', 'Amaze 1.2',
       'Amaze 1.5', 'Aria Pleasure', 'Beat', 'Beat Diesel', 'Beat LS',...
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)],
                                                                handle_unknown='ignore'),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('decisiontreeregressor',
                 DecisionTreeRegressor(random_state=4231))])

In [45]:
y_pred_dt = pipe_dt.predict(X_test)

In [46]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score

mse_dt  = mean_squared_error(y_test,y_pred_dt)
rmse_dt  = root_mean_squared_error(y_test,y_pred_dt)
r2_dt=  r2_score(y_test,y_pred_dt)

#print(mse_dt)
print(rmse_dt)
print()
print(r2_dt)

668464.0814165251

0.20090423498400056

In [47]:
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
# Random forest ?
# Xgboost ??

In [48]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor()
# pipeline building
from sklearn.pipeline import make_pipeline
pipe_rf = make_pipeline(column_trans,rf)

In [49]:
pipe_rf.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['3 Series', '5 Series', '7 Series', 'A3 Cabriolet', 'A4 1.8',
       'A4 2.0', 'A6 2.0', 'A8', 'Accent', 'Accent Executive',
       'Accent GLE', 'Accent GLX', 'Accord', 'Amaze', 'Amaze 1.2',
       'Amaze 1.5', 'Aria Pleasure', 'Beat', 'Beat Diesel', 'Beat LS',...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)],
                                                                handle_unknown='ignore'),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('randomforestregressor', RandomForestRegressor())])

In [50]:
y_pred_rf = pipe_rf.predict(X_test)

In [51]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score

mse_rf  = mean_squared_error(y_test,y_pred_rf)
rmse_rf  = root_mean_squared_error(y_test,y_pred_rf)
r2_rf=  r2_score(y_test,y_pred_rf)

#print(mse_rf)
print(rmse_rf)
print()
print(r2_rf)

676211.300937525

0.18227452935239707

In [69]:
#Xgboost
from xgboost import XGBRegressor

xgbr =  XGBRegressor(learning_rate= 0.9)

# pipeline building
from sklearn.pipeline import make_pipeline
pipe_xgbr = make_pipeline(column_trans,xgbr)

pipe_xgbr.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['3 Series', '5 Series', '7 Series', 'A3 Cabriolet', 'A4 1.8',
       'A4 2.0', 'A6 2.0', 'A8', 'Accent', 'Accent Executive',
       'Accent GLE', 'Accent GLX', 'Accord', 'Amaze', 'Amaze 1.2',
       'Amaze 1.5', 'Aria Pleasure', 'Beat', 'Beat Diesel', 'Beat LS',...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.9,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [70]:
y_pred_xgbr = pipe_xgbr.predict(X_test)

In [71]:

mse_xgbr  = mean_squared_error(y_test,y_pred_xgbr)
rmse_xgbr  = root_mean_squared_error(y_test,y_pred_xgbr)
r2_xgbr =  r2_score(y_test,y_pred_xgbr)

#print(mse_rf)
print(rmse_xgbr)
print()
print(r2_xgbr)

663723.75

0.21219748258590698

In [73]:
import joblib
joblib.dump(pipe_xgbr,"xgboost.pkl",)

['xgboost.pkl']

In [75]:
df["name"].unique()

array(['Santro Xing', 'Jeep CL550', 'Grand i10', 'EcoSport Titanium',
       'Figo', 'Eon', 'EcoSport Ambiente', 'Suzuki Alto', 'Fabia Classic',
       'Suzuki Stingray', 'Elite i20', 'Scorpio SLE', 'A8', 'Q7',
       'Scorpio S10', 'i20 Sportz', 'Suzuki Vitara', 'Bolero DI',
       'Suzuki Swift', 'Suzuki Wagon', 'Innova 2.0', 'Lodgy 85',
       'Yeti Ambition', 'Suzuki Baleno', 'Duster 110', 'Duster 85',
       'City 1.5', 'Suzuki Dzire', 'Amaze', 'Amaze 1.5', 'City',
       'Redi GO', 'Suzuki SX4', 'Pajero Sport', 'City ZX', 'Indigo eCS',
       'Polo Highline', 'Spark LS', 'Duster 110PS', 'Cooper S',
       'Fabia 1.2L', 'Duster', 'Scorpio S4', 'Scorpio VLX', 'Quanto C8',
       'EcoSport', 'Brio', 'Vento Highline', 'i20 Magna', 'Corolla Altis',
       'Verna Transform', '3 Series', 'Suzuki A', 'Etios GD',
       'Figo Diesel', 'Beat LT', '7 Series', 'XUV500 W8', 'i10 Magna',
       'Verna Fluidic', 'Suzuki Ertiga', 'Amaze 1.2', 'i20 Asta',
       'Suzuki Eeco', 'Suzuki Esteem', 'Suzuki Ritz', 'Etios Liva',
       'Spark', 'Micra XV', 'Beat', 'EcoSport Trend', 'Indica V2',
       'Motors Ambassador', 'Innova 2.5', 'Jetta Highline',
       'Polo Comfortline', 'Polo', 'Scorpio', 'Sunny', 'Kwid', 'Spark LT',
       'Punto Emotion', 'i10 Sportz', 'Beat LS', 'Indigo CS', 'Eon Era',
       'XUV500', 'Fiesta', 'i20', 'Fluidic Verna', 'Petra ELX',
       'Suzuki Ciaz', 'Suzuki Zen', 'Creta 1.6', 'Scorpio SLX', 'Nano Cx',
       'Sumo Victa', 'Passat Diesel', 'Scala RxL', 'i20 Active',
       'Xylo E4', 'Jeep MM', 'Bolero SLE', 'Motors Force', 'Etios',
       'City VX', 'Thar CRDe', 'A4 1.8', 'Benz GLA', 'Rover Freelander',
       'Kwid RXT', 'Aria Pleasure', 'Benz B', 'GO T', 'Jazz VX',
       'Tavera Neo', 'Eon Sportz', 'Sumo Gold', 'Enjoy 1.4', 'Terrano XL',
       'Suzuki Maruti', 'Kwid 1.0', 'Accent GLX', 'TUV300 T4', 'Accord',
       'Scorpio 2.6', 'Mobilio', 'Laura', 'Manza Aura', 'Sail UVA',
       'A4 2.0', 'Elantra SX', 'KUV100 K8', 'i10', 'Accent', 'Verna',
       'Fortuner', 'Bolero Power', 'Rapid Elegance', 'Vista Quadrajet',
       'Beat Diesel', 'Verna 1.4', 'Suzuki Versa', 'Indigo LX',
       'Vento Konekt', 'Benz C', 'Suzuki Omni', 'Sonata Transform',
       'Jazz S', 'Scorpio W', 'Brio V', 'TUV300 T8', 'X Trail',
       'Ikon 1.3', 'Fortuner 3.0', 'Manza ELAN', 'Benz A', 'Indigo LS',
       'Verna 1.6', '5 Series', 'Superb 1.8', 'Q3 2.0', 'Figo Duratorq',
       'Logan Diesel', 'Nano GenX', 'City SV', 'Figo Petrol',
       'Corolla H2', 'Xcent Base', 'Accent Executive', 'Zest XE',
       'XUV500 W6', 'Tigor Revotron', 'Suzuki 800', 'Mobilio S', 'Indica',
       'Brio VX', 'Nano Lx', 'XE XE', 'Eon Magna', 'Eon D',
       'Suzuki Estilo', 'Scorpio Vlx', 'Lancer 1.8', 'Fiesta SXi',
       'A6 2.0', 'Getz Prime', 'Santro', 'Beat PS', 'X1 xDrive20d',
       'Nano', 'Cruze LTZ', 'XUV500 W10', 'Accent GLE', 'Motors One',
       'Spark 1.0', 'Duster 85PS', 'Enjoy', 'Wrangler Unlimited',
       'Verna VGT', 'Suzuki Celerio', 'Zest Quadrajet', 'i10 Era',
       'Indigo Marina', 'Xcent SX', 'Nano LX', 'Xylo E8', 'Manza Aqua',
       'Venture EX', 'Octavia Classic', 'Ikon 1.6', 'Sunny XL',
       'Polo Trendline', 'Elantra 1.8', 'Indica eV2', 'XF 2.2', 'Q5 2.0',
       'X1 sDrive20d', 'Suzuki S', 'Vento Comfortline', 'KUV100',
       'Jetta Comfortline', 'S80 Summum', 'X1', 'Duster RxL', 'WR V',
       'Scorpio LX', 'A3 Cabriolet', 'Santro AE', 'Xylo D2', 'Getz GLE',
       'Micra XL', 'Tavera LS', 'Tiago Revotron', 'Tiago Revotorq',
       'Fusion 1.4', 'Linea Emotion', 'Corolla', 'Sumo Grande',
       'Polo Highline1.2L', 'Creta', 'Bolt XM', 'Go Plus', 'Endeavor 4x4',
       'Logan', 'Sail 1.2', 'Manza', 'Etios G', 'Qualis', 'Quanto C4',
       'i20 Select', 'Getz', 'Fabia', 'Zest XM'], dtype=object)